# Generated by Django 2.1.4 on 2020-11-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('image', models.BinaryField()),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'cats',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
