# Generated by Django 2.1.4 on 2020-11-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201119_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatNoImage',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'cats',
                'managed': True,
            },
        ),
    ]
