# Generated by Django 2.1.4 on 2020-11-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_catnoimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatNoImage',
            new_name='Cat',
        ),
    ]
